name: Cloud
main: System\Cloud
version: 1.0.0
api: 3.0.0-ALPHA12
author: RushEnte
commands:
  Server:
    description: Server Manager Command
    aliases: [server,pm]
  Pun:
    description: Cloud Ban Command
    aliases: [ban]
  Unpun:
    description: Cloud Unban Command
    aliases: [unban]
